#!/bin/sh

set -e

[ `git rev-parse --abbrev-ref HEAD` != master ] && exit 0

cd ..
rm -f crandalf_*.tar.gz
R CMD build crandalf
R CMD INSTALL crandalf_*.tar.gz
cd crandalf

# create branches from the current master if they do not exist
for i in `grep -G '^package:' inst/config/PACKAGES | sed 's@^package:\s*@pkg/@' | sed 's/\s*//'`;
do
  if git show-ref --verify --quiet refs/heads/$i; then
    git branch -D $i
  fi
  git checkout -b $i
  git rebase master
  Rscript -e "crandalf:::branch_update()"
  echo `git add -A && git commit -m"${USER} updated branch ${i} $(date)"`
  git checkout master
  sleep 1
done
