#!/bin/bash

set -o pipefail

rm -rf travis_done

Rscript cran-check.R | tee travis_out && echo 0 > travis_done || touch travis_done &
sleep 5

while [ ! -e travis_done ];
do
  sleep 1
  rm travis_out 2> /dev/null || [ $(date +%S) == 30 ] && echo .
done

[ -s travis_done ] || exit 1

