#!/bin/bash

which R && exit 0

cd /tmp
rm R-* -rf
wget http://cran.rstudio.com/src/base/R-3/R-3.2.0.tar.gz
tar zxf R-*.tar.gz
rm R-*.tar.gz
[ -d ~/R-base ] || mkdir ~/R-base
cp -r R-*/* ~/R-base/
cd ~/R-base
./tools/rsync-recommended
./configure --enable-R-shlib
make -j2
ln -s $PWD/bin/R ~/bin/
ln -s $PWD/bin/Rscript ~/bin/
R --version
R CMD javareconf
