#!/bin/bash

NEED_REINSTALL=$(git log --format=%B --no-merges -n 1 | grep -E "\[reinstall pandoc\]")
if [ ! -z "$NEED_REINSTALL" ]
then
  rm -rf ~/bin/pandoc*
fi

[ ! -d ~/bin ] && mkdir ~/bin
export PATH=$PATH:$HOME/bin

[ -e ~/bin/pandoc ] && pandoc --version && exit 0

cd ~
wget -q https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz
tar zxf pandoc.tar.gz
rm pandoc.tar.gz
chmod +x pandoc pandoc-citeproc
mv pandoc pandoc-citeproc $HOME/bin/
pandoc --version
