#!/bin/bash

[ -e ~/texlive ] && exit 0

cd ~

wget https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz
tar zxf texlive.tar.gz
pdflatex --version
# now you can use `tlmgr install` to install whatever package you want
