#!/bin/bash

export PATH=$HOME/texlive/bin/x86_64-linux:$PATH

texlive_pkgs() {
  wget -q https://github.com/yihui/ubuntu-bin/raw/master/TeXLive.pkgs
  [ -e $HOME/texlive/bin/x86_64-linux/tlmgr ] && tlmgr install $(cat TeXLive.pkgs | tr '\n' ' ') > /dev/null
  tlmgr update --all
  mktexlsr
  rm TeXLive.pkgs
}

texlive_pkgs
[ -e $HOME/texlive/bin/x86_64-linux/pdflatex ] && exit 0

cd $HOME

wget -q https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz
tar zxf texlive.tar.gz
pdflatex --version
# now you can use `tlmgr install` to install whatever package you want
texlive_pkgs
