#!/bin/bash

which pandoc && exit 0
export PATH=$PATH:$HOME/bin

cd ~
wget -q https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz
tar zxf pandoc.tar.gz
rm pandoc.tar.gz
chmod +x pandoc pandoc-citeproc
mv pandoc pandoc-citeproc ~/bin/
pandoc --version
