on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * * '

name: rev-check

jobs:
  rev-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@HEAD

      - name: Checkout your package
        uses: actions/checkout@HEAD
        with:
          path: package
          # change the repo below to yours
          repository: yihui/knitr
          # ref: master

      - name: Clean up .Renviron
        run: |
          sed -i '' /R_LIBS_USER/d .Renviron

      - uses: r-lib/actions/setup-r@HEAD
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-tinytex@HEAD
        env:
          TINYTEX_INSTALLER: TinyTeX

      - uses: r-lib/actions/setup-pandoc@HEAD

      - uses: yihui/actions/setup-r-dependencies@HEAD
        with:
          brew-packages: xquartz
          extra-packages: rmarkdown litedown .

      - name: Check reverse dependencies
        run: |
          Rscript R/setup.R
          Rscript R/revcheck.R

      - name: Upload check results
        uses: actions/upload-artifact@main
        if: failure()
        with:
          name: ${{ runner.os }}-rev-check-results
          if-no-files-found: ignore
          path: |
            00check_diffs.html
            latex.txt
            recheck
            recheck2
            *.Rcheck
            *.Rcheck2
